name: CI

on: [pull_request, push]

jobs:
  macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test target
        run: swift test -v
  iOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test target
        run: >
          swift test -v
          -Xswiftc "-sdk"
          -Xswiftc "`xcrun --sdk iphonesimulator --show-sdk-path`"
          -Xswiftc "-target" -Xswiftc "x86_64-apple-ios13-simulator"
